"""Resolve a runtime lock from pyproject.toml without modifying the environment.

Run with the supported Python version after intentionally updating direct pins;
review and test the lock on Linux before deployment.
"""

import json
import subprocess
import sys
import tempfile
import tomllib
from pathlib import Path


def main():
    root = Path(__file__).resolve().parents[1]
    project = tomllib.loads((root / "pyproject.toml").read_text(encoding="utf-8"))
    with tempfile.TemporaryDirectory(prefix="scj-lock-") as directory:
        report = Path(directory) / "resolution.json"
        subprocess.run([sys.executable, "-m", "pip", "install", "--dry-run", "--ignore-installed",
                        "--report", str(report), *project["project"]["dependencies"]], check=True)
        resolved = json.loads(report.read_text(encoding="utf-8"))
    pins = sorted(f"{p['metadata']['name'].lower()}=={p['metadata']['version']}"
                  for p in resolved["install"])
    (root / "requirements.lock").write_text(
        "# Generated by scripts/lock_dependencies.py; validate on Linux before release.\n"
        + "\n".join(pins) + "\n", encoding="utf-8"
    )


if __name__ == "__main__":
    main()
